# Generated by Django 6.0.5 on 2026-05-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadoquiz',
            old_name='fecha_realizacion',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='senafavorita',
            old_name='fecha_guardado',
            new_name='fecha_agregada',
        ),
        migrations.AlterUniqueTogether(
            name='senafavorita',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('opcion_1', models.CharField(max_length=100)),
                ('opcion_2', models.CharField(max_length=100)),
                ('opcion_3', models.CharField(max_length=100)),
                ('opcion_4', models.CharField(max_length=100)),
                ('respuesta_correcta', models.IntegerField(help_text='Ingresa 1, 2, 3 o 4')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='api.modulo')),
            ],
        ),
    ]
